---
source: compiler/e2e/test/snapshot/mod.rs
expression: clean_run
---
stderr:
error: access is done while it is mutably borrowed
   ╭─ compiler/e2e/test/snapshot/borrow_checker/mutably_access_more_than_once_in_function/main.pnx:21:17
   │
20 │     vector.push(&mut number)
   │                 ----------- the mutable borrow starts here
21 │     vector.push(&mut number)
   │     ------      ^^^^^^^^^^^ access occurs here while it is mutably borrowed
   │     │            
   │     the borrow is used here

error: Compilation aborted due to 1 error(s)



stdout:
